// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppLab3.Data;

#nullable disable

namespace WebAppLab3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240319121911_addedallflights")]
    partial class addedallflights
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("WebAppLab3.Models.ContactUsEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactUsEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@gmail.com",
                            Message = "Hello",
                            Timestamp = new DateTime(2024, 3, 19, 14, 19, 11, 467, DateTimeKind.Local).AddTicks(7731)
                        });
                });

            modelBuilder.Entity("WebAppLab3.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explore the romantic charm of the City of Lights, visit iconic landmarks like the Eiffel Tower, and indulge in exquisite French cuisine.",
                            ImagePath = "/images/paris.jpg",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Immerse yourself in the vibrant energy of Tokyo, experience a blend of modernity and tradition, and discover the unique cultural wonders of Japan.",
                            ImagePath = "/images/tokyo.jpg",
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dive into the bustling metropolis of New York City, witness the dazzling lights of Times Square, and explore world-renowned attractions like Central Park and the Statue of Liberty.",
                            ImagePath = "/images/new_york.jpg",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Embark on a journey to Rio de Janeiro, where the lively rhythm of samba meets stunning beaches, iconic landmarks like Christ the Redeemer, and the vibrant Carnival spirit.",
                            ImagePath = "/images/rio.jpg",
                            Name = "Rio de Janeiro"
                        });
                });

            modelBuilder.Entity("WebAppLab3.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A1",
                            Price = 250
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A2",
                            Price = 250
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A3",
                            Price = 250
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A4",
                            Price = 250
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A5",
                            Price = 250
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A6",
                            Price = 250
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A7",
                            Price = 250
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A8",
                            Price = 250
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A9",
                            Price = 250
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A10",
                            Price = 250
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A11",
                            Price = 250
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A12",
                            Price = 250
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A13",
                            Price = 250
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A14",
                            Price = 250
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A15",
                            Price = 250
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A16",
                            Price = 250
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A17",
                            Price = 250
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A18",
                            Price = 250
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A19",
                            Price = 250
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 1,
                            IsBooked = false,
                            Number = "A20",
                            Price = 250
                        },
                        new
                        {
                            Id = 21,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B1",
                            Price = 450
                        },
                        new
                        {
                            Id = 22,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B2",
                            Price = 450
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B3",
                            Price = 450
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B4",
                            Price = 450
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B5",
                            Price = 450
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B6",
                            Price = 450
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B7",
                            Price = 450
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B8",
                            Price = 450
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B9",
                            Price = 450
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B10",
                            Price = 450
                        },
                        new
                        {
                            Id = 31,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B11",
                            Price = 450
                        },
                        new
                        {
                            Id = 32,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B12",
                            Price = 450
                        },
                        new
                        {
                            Id = 33,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B13",
                            Price = 450
                        },
                        new
                        {
                            Id = 34,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B14",
                            Price = 450
                        },
                        new
                        {
                            Id = 35,
                            FlightId = 2,
                            IsBooked = false,
                            Number = "B15",
                            Price = 450
                        },
                        new
                        {
                            Id = 36,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C1",
                            Price = 1050
                        },
                        new
                        {
                            Id = 37,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C2",
                            Price = 1050
                        },
                        new
                        {
                            Id = 38,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C3",
                            Price = 1050
                        },
                        new
                        {
                            Id = 39,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C4",
                            Price = 1050
                        },
                        new
                        {
                            Id = 40,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C5",
                            Price = 1050
                        },
                        new
                        {
                            Id = 41,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C6",
                            Price = 1050
                        },
                        new
                        {
                            Id = 42,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C7",
                            Price = 1050
                        },
                        new
                        {
                            Id = 43,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C8",
                            Price = 1050
                        },
                        new
                        {
                            Id = 44,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C9",
                            Price = 1050
                        },
                        new
                        {
                            Id = 45,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C10",
                            Price = 1050
                        },
                        new
                        {
                            Id = 46,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C11",
                            Price = 1050
                        },
                        new
                        {
                            Id = 47,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C12",
                            Price = 1050
                        },
                        new
                        {
                            Id = 48,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C13",
                            Price = 1050
                        },
                        new
                        {
                            Id = 49,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C14",
                            Price = 1050
                        },
                        new
                        {
                            Id = 50,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C15",
                            Price = 1050
                        },
                        new
                        {
                            Id = 51,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C16",
                            Price = 1050
                        },
                        new
                        {
                            Id = 52,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C17",
                            Price = 1050
                        },
                        new
                        {
                            Id = 53,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C18",
                            Price = 1050
                        },
                        new
                        {
                            Id = 54,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C19",
                            Price = 1050
                        },
                        new
                        {
                            Id = 55,
                            FlightId = 3,
                            IsBooked = false,
                            Number = "C20",
                            Price = 1050
                        },
                        new
                        {
                            Id = 56,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A1",
                            Price = 350
                        },
                        new
                        {
                            Id = 57,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A2",
                            Price = 350
                        },
                        new
                        {
                            Id = 58,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A3",
                            Price = 350
                        },
                        new
                        {
                            Id = 59,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A4",
                            Price = 350
                        },
                        new
                        {
                            Id = 60,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A5",
                            Price = 350
                        },
                        new
                        {
                            Id = 61,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A6",
                            Price = 350
                        },
                        new
                        {
                            Id = 62,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A7",
                            Price = 350
                        },
                        new
                        {
                            Id = 63,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A8",
                            Price = 350
                        },
                        new
                        {
                            Id = 64,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A9",
                            Price = 350
                        },
                        new
                        {
                            Id = 65,
                            FlightId = 4,
                            IsBooked = false,
                            Number = "A10",
                            Price = 350
                        });
                });

            modelBuilder.Entity("WebAppLab3.Models.Seat", b =>
                {
                    b.HasOne("WebAppLab3.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("WebAppLab3.Models.Flight", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
